DROP database IF EXISTS `jpa_JBD`;

CREATE database IF NOT EXISTS `jpa_JBD`;
use `jpa_JBD`;

CREATE TABLE `TEACHER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TEACHERTNAME` varchar(45) DEFAULT NULL,
  `SUBJECT` varchar(45) DEFAULT NULL,
  `DEGREE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


INSERT INTO `TEACHER` (`ID`,`TEACHERTNAME`,`SUBJECT`,`DEGREE`) VALUES (1,'JAYANTA','JAVA BACKEND','PHD');
